New Spezi Standard Implementation
StanfordSpezi/SpeziScheduler pull request #24
Opened 2023-07-31 21:47 UTC by niallkehoe

# *Name of the PR*

## :recycle: Current situation & Problem
Currently, the SpeziScheduler module lacks support for the new Spezi Standard released in Spezi 0.7.0
*This PR implements the improvements mentioned in [https://github.com/https://github.com/StanfordSpezi/Spezi/pull/73](Pull 73) *

## :bulb: Proposed solution
Update the codebase to the newest Spezi 0.7.0

## :gear: Release Notes 
This feature will allow for greater flexibility when using Spezi Questionnaire.

```
/// an example Standard used for the configuration.
actor ExampleStandard: Standard, ObservableObjectProvider, ObservableObject { }
```

### Related PRs
See [https://github.com/https://github.com/StanfordSpezi/Spezi/pull/73](Pull 73) in Spezi for details

### Testing
Passes all tests

### Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md):
- [✅ ] I agree to follow the [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md).

2023-08-01 22:31 UTC, vishnuravi commented
Nice work @niallkehoe!

2023-08-01 22:32 UTC, PSchmiedmayer requested changes
Very nice, some small changes, only a few smaller feedback comments that I added in the files. 

It would also be needed to slightly adjust the documentation and remove all mentions of standards in the comments and .md files. E.g. you can remove the last sentence and code example in `SchedulingATask.md`.

You can also remove the `SchedulerTestsStandard` type in the `SchedulerTests.swift` file.

2023-08-01 22:32 UTC, PSchmiedmayer commented on Tests/UITests/TestApp/ExampleStandard.swift
You can remove this type here, as we don't need to explicitly define it in the `Configuration`.

2023-08-01 22:32 UTC, PSchmiedmayer commented on Tests/UITests/TestApp/TestAppDelegate.swift
> +        Configuration(standard: ExampleStandard()) {
You should be able to completely go without a `Standard` here as we don't have any requirements on the standard and can just inject a default instance that is used within Spezi.
```suggestion
        Configuration {
```

2023-08-01 22:32 UTC, PSchmiedmayer commented on Tests/UITests/TestApp/TestAppDelegate.swift
> +import Foundation
I don't think that the import statement would be needed here:
```suggestion
```

2023-08-02 21:54 UTC, niallkehoe commented
@PSchmiedmayer Interesting that this fails the tests on the Github Action but passes all tests on my machine. Any ideas?
        TestAppUITests.testSchedulerBackgroundNotifications()
	TestAppUITests.testSchedulerNotifications()
	TestAppUITests.testSchedulerNotificationsBeforePermissions()

2023-08-05 21:56 UTC, PSchmiedmayer approved these changes

2023-08-05 21:58 UTC, PSchmiedmayer commented
@niallkehoe I have taken a look at the testing issues and it seems like this is related to a runtime crash due to some async overloads of the [`UNUserNotificationCenterDelegate `](https://developer.apple.com/documentation/usernotifications/unusernotificationcenterdelegate) protocol.

I could reproduce the crashes in the UI tests using Xcode 15 and using an iOS 17 simulator.

I have moved the code to the completion-based version of the methods in this commit: https://github.com/StanfordSpezi/SpeziScheduler/pull/24/commits/aa271b81bceaf831ab060c8f00b794edb9245f75

2023-08-05 22:52 UTC, merged